[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "BioProcessing"
versionNumber = "1.0.1"
description = "Biological processing system with algae vats, mushroom farms, bio-reactors, and composters. Produces biofuel and biogas from organic materials."
websiteUrl = "https://github.com/xXDeath420Xx/TTMod-BioProcessing"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/BioProcessing.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
